version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - mongo-compose-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    links:
      - mongodb
    networks:
      - mongo-compose-network
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://rootuser:rootpass@mongodb:27017/
  codebrain-backend:
    networks:
      - mongo-compose-network
    ports:
      - '8080:8080'
    links:
      - mongodb
      - mongo-express
    image: romulolobof/codebrain-spring-docker:latest
    container_name: codebrain-spring-docker
volumes:
  data: {}
networks:
  mongo-compose-network:
    driver: bridge
